### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by My12123** [1439707509/pygui#6]
```python
(trans) F:\Загрузки\manga-image-translator pygui\trans\trans>python win.py
Traceback (most recent call last):
  File "F:\Загрузки\manga-image-translator pygui\trans\trans\win.py", line 13, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

**Comment by Craxti** [comment]
sudo pip3 install dotenv

**Comment by My12123** [comment]
I use windows 10

**Comment by My12123** [comment]
```python
(trans) F:\Загрузки\manga-image-translator pygui\trans\trans>pip install dotenv
Collecting dotenv
  Downloading dotenv-0.0.5.tar.gz (2.4 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Collecting distribute
        Downloading distribute-0.7.3.zip (145 kB)
           ------------------------------------ 145.4/145.4 kB 958.4 kB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1

        [6 lines of output]
        usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
           or: setup.py --help [cmd1 cmd2 ...]
           or: setup.py --help-commands
           or: setup.py cmd --help

        error: invalid command 'dist_info'
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by 1439707509** [comment]
> ```python
> (trans) F:\Загрузки\manga-image-translator pygui\trans\trans>python win.py
> Traceback (most recent call last):
>   File "F:\Загрузки\manga-image-translator pygui\trans\trans\win.py", line 13, in <module>
>     from dotenv import load_dotenv
> ModuleNotFoundError: No module named 'dotenv'
> ```

下载最新的发行版，放在d盘根目录下运行
