### ISSUE TITLE
ModuleNotFoundError: No module named 'pydensecrf'

### ISSUE THREAD

**Issue by My12123** [1439707509/pygui#7]
```python
(trans) F:\Загрузки\manga-image-translator pygui\trans\trans>python -m manga_translator -v --mode batch --use-cuda --translator=papago -l RUS --font-path=fonts/anime_ace.ttf --colorizer mc2 -i I:\Free\1
Traceback (most recent call last):
  File "C:\Users\tchot\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\tchot\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\tchot\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "F:\Загрузки\manga-image-translator pygui\trans\trans\manga_translator\__init__.py", line 7, in <module>
    from .manga_translator import *
  File "F:\Загрузки\manga-image-translator pygui\trans\trans\manga_translator\manga_translator.py", line 40, in <module>
    from .mask_refinement import dispatch as dispatch_mask_refinement
  File "F:\Загрузки\manga-image-translator pygui\trans\trans\manga_translator\mask_refinement\__init__.py", line 6, in <module>
    from .text_mask_utils import complete_mask_fill, filter_masks, complete_mask
  File "F:\Загрузки\manga-image-translator pygui\trans\trans\manga_translator\mask_refinement\text_mask_utils.py", line 96, in <module>
    from pydensecrf.utils import compute_unary, unary_from_softmax
ModuleNotFoundError: No module named 'pydensecrf'
``` 

![2023-05-30_20-18-22](https://github.com/1439707509/pygui/assets/49092250/3fa30af2-bc2e-4c89-8702-4bc457df0716)

```python
rootdir= F:\Загрузки\manga-image-translator pygui\trans\trans
开始执行
F:\Загрузки\manga-image-translator pygui\trans\trans\Scripts\python.exe -m manga_translator --mode batch --target-lang=CHS   -i I:/Free/1 -o I:/Free/1-0  -f png --translator=gpt4 --detector default  --colorizer mc2 --colorization-size -1   --ocr 48px_ctc
poll= 40028
开始执行，cmd=F:\Загрузки\manga-image-translator pygui\trans\trans\Scripts\python.exe -m manga_translator --mode batch --target-lang=CHS   -i I:/Free/1 -o I:/Free/1-0  -f png --translator=gpt4 --detector default  --colorizer mc2 --colorization-size -1   --ocr 48px_ctc   --use-cuda
"F:\Загрузки\manga-image-translator" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом
```

**Comment by 1439707509** [comment]
能不能放在d盘下运行？我所有第三库都写死在d盘

**Comment by 1439707509** [comment]
如果你没有d盘，可以招这个操做，改硬盘盘符
https://jingyan.baidu.com/article/d8072ac48f8332ad95cefda8.html
